# Generated by Django 2.2 on 2020-12-12 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='madeBy',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
